### PR TITLE
Spelling correction

### PR DESCRIPTION
**Pull request by roshni13khincha**
Corrected untiofobs to unitofobs

### CODE REVIEW

**Comment by kbjarkefur** [comment]
Hi @roshni13khincha , thank you for catching these typos. I had hoped to meet you in person as I am in the office today but @luizaandrade told me you will be traveling these days.

We really appreciate contributions from anyone so I feel bad asking you to submit your edit in a slightly different way. I am not sure how familiar you are with GitHub terminology, but the `master` branch is only edited when a new version of **ietoolkit** is released. You do not need to to understand what I just said, but if you want to submit your edits again and get contribution credit for them (which I think you should), click [here](https://github.com/worldbank/ietoolkit/blob/develop/src/help_files/iefolder.sthlp) and make the exact same changes in the exact same way there. It is the same file, but in a different branch of the repository. Your edit will then be included in the next version of **ietoolkit** and be merged to the master branch then.

Let me know if you have any questions or you can ask @luizaandrade when you are back.

**Comment by roshni13khincha** [comment]
Hi @kbjarkefur,

Thanks for informing me about the correct way of submitting edits. @luizaandrade explained the same to me last week and in case I find further corrections, I will submit requests to the Develop branch. 

It is a shame that I miss meeting you during your visit this week.  Hope to meet you the next time you are around.

**Comment by kbjarkefur** [comment]
Ok, thanks! I will keep this PR open until we merge the next one. I will have to reject this one, and if you want the contribution recognition you need to re-submit these edits to the `develop` branch. I can do it as well if you do not want to, but I think you should do it to practice GitHub skills and to get the contribution recognition. But no stress, just do this on your own time.

**Comment by roshni13khincha** [comment]
@kbjarkefur Just re-submitted the edit to the develop branch.

**Comment by kbjarkefur** [comment]
Thank you @roshni13khincha ! I merged the other PR, and will now close this one.

**Pull request closed without merging**
