### PR TITLE
Issue 121

### PR DESCRIPTION
**Pull request by luizaandrade**
I think this is ready to go. Might be good to get some fresh eyes to:
1. check if the help file is clear
2. run a different testing do-file

### CODE REVIEW

**Comment by kbjarkefur** [comment]
Memory note: Remove the .tex file and the meta files from generating the pdf before merging, but they are actually quite helpful to have for me.

**Comment by kbjarkefur** [comment]
image

I found an error here. See the titles goes first test (1)-(2) with both ttest and normdiff, then test (1)-(3) both tests, but the results goes first all ttest results and then all normdiff results.

**Comment by luizaandrade** [comment]
@kbjarkefur, the issue has been fixed. I have added two programs to create the headers, but they can also be written as a single program, Let me know what you think?

**Comment by kbjarkefur** [comment]
@luizaandrade , I think this is fine, but for next time, I think the [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) would probably be slightly better way to go. If we do the BIG re-write of **iebaltab** I think we should have two programs, one that makes a list of the test pairs (thats the difference between control and no control) and one that write the headers based on that list. That way we isolate each task, and do not need to repeat code in different programs. But I do not think we need to re-write this, I am mostly saying this as guidance to next time you have a similar situation, or to when we do re-write this command.

I have not tested the header fix. Let me know if you want me to do that, but it should be fine and I think we should just be able to merge this.

**Pull request merged**
