### PR TITLE
iefolder : fix issue #124 - create housekeeping command called ietoolkit

### PR DESCRIPTION
**Pull request by eatorange**
Update to "iefolder" command
 - project master do-file, which the command creates, will install packages only if those packages are NOT installed in the system

Co-Authored-By: Kristoffer Bjärkefur <kbjarkefur@users.noreply.github.com>

### CODE REVIEW

**Comment by kbjarkefur** [comment]
Perfect! Thanks! @eatorange

**Comment by kbjarkefur** [comment]
@eatorange , don't worry about this in case you do not have time. I am using this and I think it is great, but I wonder why we have the second `cap` on row 897 in the file changed. If a user do not have a command it should be installed, but if it can't be installed, shouldn't it return an error then? Or do we think it is better to ignore it at this point and let it only cause an error if/when that command is actually used? I do not know what I prefer, I just wondered if this is something that you thought of when you wrote this

**Comment by eatorange** [comment]
@kbjarkefur That's strange. I checked my original code and I don't use the second "cap" like the one you found on row 897... Maybe someone else added it?

**Comment by eatorange** [comment]
Or maybe I added it by mistake (or something I cant remember). No matter what the reason is, that "cap" won't be necessary.

**Comment by kbjarkefur** [comment]
It could have been me when I looked into the code. But it doesn't matter where it came from, more important is what we want to do next. I agree with how you had it originally with no second `cap` , so I'll remove it. Thanks!

**Pull request merged**
